import type { TipMeta } from '..';

export const meta: TipMeta = {
  slug: 'collection',
  title: '',
  shortDescription: '',
  writtenOn: '2025-08-11',
  keywords: ['C#' as const],
  metadata: {
    searchKeywords: [
      'collections',
      'collection',
      'ienumerable',
      'icollection',
      'ilist',
      'ireadonlycollection',
      'list',
      'array',
      'tableau',
      'énumération',
      'enumeration',
      'itération',
      'iteration',
      'foreach',
      'linq',
      'count',
      'add',
      'remove',
      'indexer',
      'générique',
      'generic',
    ],
    tags: ['collections', 'linq', 'c#'],
  },
};
