import type { TipMeta } from '..';

export const meta: TipMeta = {
  slug: 'collection',
  title: '',
  shortDescription: '',
  writtenOn: '2025-08-11',
  keywords: ['C#' as const],
  metadata: {
    searchKeywords: {
      fr: [
        'collections',
        'collection',
        'ienumerable',
        'icollection',
        'ilist',
        'ireadonlycollection',
        'list',
        'array',
        'tableau',
        'énumération',
        'itération',
        'foreach',
        'linq',
        'count',
        'add',
        'remove',
        'indexer',
        'générique',
      ],
      en: [
        'collections',
        'collection',
        'ienumerable',
        'icollection',
        'ilist',
        'ireadonlycollection',
        'list',
        'array',
        'enumeration',
        'iteration',
        'foreach',
        'linq',
        'count',
        'add',
        'remove',
        'indexer',
        'generic',
      ],
    },
  },
};
