import type { TipMeta } from '..';

export const meta: TipMeta = {
  slug: 'dotnet-11-runtime-async',
  title: '',
  shortDescription: '',
  writtenOn: '2026-08-19',
  categories: ['.NET 11', 'C#', 'Async', 'Performance'],
  searchKeywords: [
    'runtime async',
    'runtime-async',
    '.net 11',
    'dotnet 11',
    'async',
    'await',
    'task',
    'state machine',
    'machine a etats',
    'movenext',
    'iasyncstatemachine',
    'asynchelpers',
    'allocations',
    'performance',
    'stack trace',
    'pile d appels',
    'debogage',
    'debugging',
    'crossgen2',
    'readytorun',
    'inlining',
    'covariance task',
    'c#',
    'csharp',
  ],
};
