import type { TipMeta } from '..';

export const meta: TipMeta = {
  slug: 'spec-kit',
  title: '',
  shortDescription: '',
  writtenOn: '2026-10-03',
  categories: ['AI', 'Agents', 'Workflow'],
  searchKeywords: [
    'spec kit',
    'spec-kit',
    'speckit',
    'specify',
    'specify-cli',
    'spec driven development',
    'sdd',
    'specification',
    'constitution',
    'plan',
    'tasks',
    'github',
    'github copilot',
    'copilot',
    'claude code',
    'codex',
    'skills',
    'agents',
    'uv',
    'installation',
    'macos',
    'windows',
    'workflow',
    'bmad',
  ],
};
