import type { TipMeta } from '..';

export const meta: TipMeta = {
  slug: 'polly',
  title: '',
  shortDescription: '',
  writtenOn: '2025-08-20',
  keywords: ['C#' as const],
  metadata: {
    searchKeywords: [
      'polly',
      'résilience',
      'resilience',
      'retry',
      'tentative',
      'attempt',
      'circuit breaker',
      'timeout',
      'fallback',
      'politique',
      'policy',
      'échec',
      'failure',
      'panne',
      'fault',
      'robustesse',
      'robustness',
      'stabilité',
      'stability',
      'récupération',
      'recovery',
      'bulkhead',
      'rate limiting',
      'fault tolerance',
      'exception',
      'waitAndRetry',
    ],
    tags: ['resilience', 'retry', 'c#'],
  },
};
