import type { TipMeta } from '..';

export const meta: TipMeta = {
  slug: 'polly',
  title: '',
  shortDescription: '',
  writtenOn: '2025-08-20',
  keywords: ['C#' as const],
  metadata: {
    searchKeywords: {
      fr: [
        'polly',
        'résilience',
        'retry',
        'tentative',
        'circuit breaker',
        'timeout',
        'fallback',
        'politique',
        'échec',
        'panne',
        'robustesse',
        'stabilité',
        'récupération',
        'bulkhead',
        'rate limiting',
        'fault tolerance',
        'exception',
        'waitAndRetry',
      ],
      en: [
        'polly',
        'resilience',
        'retry',
        'attempt',
        'circuit breaker',
        'timeout',
        'fallback',
        'policy',
        'failure',
        'fault',
        'robustness',
        'stability',
        'recovery',
        'bulkhead',
        'rate limiting',
        'fault tolerance',
        'exception',
        'waitAndRetry',
      ],
    },
  },
};
