import type { TipMeta } from '..';
import type { Keyword } from '../../../utils/constants';

export const meta: TipMeta = {
  slug: 'automapper',
  title: '',
  shortDescription: '',
  writtenOn: '2025-08-14',
  keywords: ['C#'] as unknown as Keyword[],
  metadata: {
    searchKeywords: {
      fr: [
        'automapper',
        'mapping',
        'transformation',
        'conversion',
        'dto',
        'entity',
        'objet',
        'profile',
        'configuration',
        'projection',
        'flattening',
        'copie',
        'automatique',
        'convention',
        'règles',
        'validation',
        'mapFrom',
        'ignore',
      ],
      en: [
        'automapper',
        'mapping',
        'transformation',
        'conversion',
        'dto',
        'entity',
        'object',
        'profile',
        'configuration',
        'projection',
        'flattening',
        'copy',
        'automatic',
        'convention',
        'rules',
        'validation',
        'mapFrom',
        'ignore',
      ],
    },
  },
};
