import type { TipMeta } from '..';

export const meta: TipMeta = {
  slug: 'avalonia',
  title: '',
  shortDescription: '',
  writtenOn: '2026-03-06',
  categories: ['UI', 'Cross-Platform', '.NET'],
  searchKeywords: [
    'avalonia',
    'avalonia ui',
    'avaloniaui',
    'cross-platform',
    'xaml',
    'wpf alternative',
    'ui framework',
    'dotnet',
    '.net',
    'maui',
    'mobile',
    'ios',
    'android',
    'windows',
    'macos',
    'linux',
    'wasm',
    'webassembly',
    'skia',
    'mvvm',
    'reactiveui',
    'single codebase',
    'bureau',
    'desktop',
    'cross platform',
    'framework ui',
    'déploiement',
    'deployment',
  ],
};
