import type { TipMeta } from '..';

export const meta: TipMeta = {
  slug: 'mcp-servers',
  title: '',
  shortDescription: '',
  writtenOn: '2025-08-27',
  keywords: ['C#' as const],
  metadata: {
    searchKeywords: {
      fr: [
        'mcp',
        'model context protocol',
        'serveur mcp',
        'copilot',
        'vscode',
        'extension mcp',
        'outils',
        'automatisation',
        'github mcp',
        'microsoft docs mcp',
        'figma mcp',
  'azure devops mcp',
  'azdo',
  'ado',
        'issues',
        'pull requests',
        'documentation',
        'design',
        'workflow',
      ],
      en: [
        'mcp',
        'model context protocol',
        'mcp server',
        'copilot',
        'vscode',
        'mcp extension',
        'tools',
        'automation',
        'github mcp',
        'microsoft docs mcp',
        'figma mcp',
  'azure devops mcp',
  'azdo',
  'ado',
        'issues',
        'pull requests',
        'documentation',
        'design',
        'workflow',
      ],
    },
  },
};
