import type { TipMeta } from '..';

export const meta: TipMeta = {
  slug: 'mcp-servers',
  title: '',
  shortDescription: '',
  writtenOn: '2025-08-27',
  keywords: ['C#' as const],
  metadata: {
    searchKeywords: [
      'mcp',
      'model context protocol',
      'serveur mcp',
      'mcp server',
      'copilot',
      'vscode',
      'extension mcp',
      'mcp extension',
      'outils',
      'tools',
      'automatisation',
      'automation',
      'github mcp',
      'microsoft docs mcp',
      'figma mcp',
      'azure devops mcp',
      'azdo',
      'ado',
      'issues',
      'pull requests',
      'documentation',
      'design',
      'workflow',
    ],
    tags: ['mcp', 'ai'],
  },
};
