import type { TipMeta } from '..';

export const meta: TipMeta = {
  slug: 'csharp-14',
  title: '',
  shortDescription: '',
  writtenOn: '2025-11-25',
  keywords: ['C#' as const],
  metadata: {
    searchKeywords: [
      'C#',
      'C# 14',
      'csharp',
      'extension members',
      'extension properties',
      'field keyword',
      'field backed properties',
      'null conditional assignment',
      'nameof',
      'unbound generic types',
      'span',
      'ReadOnlySpan',
      'implicit conversions',
      'lambda modifiers',
      'partial constructors',
      'partial events',
      'compound assignment',
      'opérateurs composés',
      'propriétés d\'extension',
      'membres d\'extension',
      'assignation conditionnelle',
      'types génériques non liés',
      'conversions implicites',
      'modificateurs lambda',
      'constructeurs partiels',
      'événements partiels',
      '.NET 10',
      'Visual Studio 2026',
    ],
    tags: ['c# 14', 'c#'],
  },
};
