import type { TipMeta } from '..';

export const meta: TipMeta = {
  slug: 'nsubstitute',
  title: '',
  shortDescription: '',
  writtenOn: '2025-08-12',
  keywords: ['C#' as const],
  metadata: {
    searchKeywords: {
      fr: [
        'nsubstitute',
        'mock',
        'mocking',
        'substitute',
        'double',
        'fake',
        'stub',
        'spy',
        'tests',
        'isolation',
        'dépendance',
        'interface',
        'simulation',
        'vérification',
        'arguments',
        'retour',
        'callback',
        'received',
        'returns',
      ],
      en: [
        'nsubstitute',
        'mock',
        'mocking',
        'substitute',
        'double',
        'fake',
        'stub',
        'spy',
        'tests',
        'isolation',
        'dependency',
        'interface',
        'simulation',
        'verification',
        'arguments',
        'return',
        'callback',
        'received',
        'returns',
      ],
    },
  },
};
