import type { TipMeta } from '..';

export const meta: TipMeta = {
  slug: 'facet',
  title: '',
  shortDescription: '',
  writtenOn: '2025-08-21',
  keywords: ['C#' as const],
  metadata: {
    searchKeywords: {
      fr: [
        'facet',
        'générateur',
        'code generation',
        'dto',
        'projections',
        'mapping',
        'ef core',
        'entity framework',
        'select',
        'compilation',
        'attributs',
        'performance',
        'requêtes',
        'optimisation',
        'source generator',
        'mapper',
      ],
      en: [
        'facet',
        'generator',
        'code generation',
        'dto',
        'projections',
        'mapping',
        'ef core',
        'entity framework',
        'select',
        'compilation',
        'attributes',
        'performance',
        'queries',
        'optimization',
        'source generator',
        'mapper',
      ],
    },
  },
};
