import type { TipMeta } from '..';

export const meta: TipMeta = {
  slug: 'bmad-method',
  title: '',
  shortDescription: '',
  writtenOn: '2026-10-02',
  categories: ['AI', 'Agents', 'Workflow'],
  searchKeywords: [
    'bmad',
    'bmad method',
    'bmad-method',
    'agile',
    'ai driven development',
    'aidd',
    'agents',
    'skills',
    'claude code',
    'codex',
    'cursor',
    'prd',
    'spec',
    'specification',
    'architecture',
    'epic',
    'story',
    'ticket',
    'code review',
    'revue de code',
    'party mode',
    'brainstorming',
    'installation',
    'macos',
    'windows',
    'workflow',
    'spec kit',
  ],
};
