import type { TipMeta } from '..';

export const meta: TipMeta = {
  slug: 'csharp-15-unions',
  title: '',
  shortDescription: '',
  writtenOn: '2026-08-19',
  categories: ['C# 15', 'C#', '.NET 11'],
  searchKeywords: [
    'csharp-15',
    'c# 15',
    'csharp',
    'c#',
    'union',
    'union types',
    'types union',
    'closed',
    'closed hierarchies',
    'hierarchies fermees',
    'discriminated union',
    'union discriminee',
    'pattern matching',
    'switch exhaustif',
    'exhaustive switch',
    'oneof',
    'result type',
    'dotnet 11',
    '.net 11',
    'sum type',
    'algebraic data type',
    'modelisation domaine',
    'domain modeling',
  ],
};
