import type { TipMeta } from '..';

export const meta: TipMeta = {
  slug: 'ef-core-11-vector-search',
  title: '',
  shortDescription: '',
  writtenOn: '2026-08-19',
  categories: ['EF Core', 'C#', 'AI', 'SQL Server'],
  searchKeywords: [
    'ef core 11',
    'efcore',
    'entity framework',
    'entity framework core',
    'vector search',
    'recherche vectorielle',
    'embedding',
    'embeddings',
    'sqlvector',
    'diskann',
    'ann',
    'approximate nearest neighbor',
    'plus proches voisins',
    'sql server 2025',
    'cosine',
    'similarite',
    'similarity',
    'rag',
    'semantic search',
    'recherche semantique',
    'full text search',
    'hybrid search',
    'microsoft.extensions.ai',
    'c#',
    'csharp',
    'dotnet 11',
  ],
};
