name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    permissions:
       id-token: write
       contents: read
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Install OIDC Client from Core Package
        run: npm install @actions/core@1.6.0 @actions/http-client
      - name: Get Id Token
        uses: actions/github-script@v6
        id: idtoken
        with:
           script: |
               const coredemo = require('@actions/core')
               return await coredemo.getIDToken()
           result-encoding: string
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies and build frontend
        run: |
          echo "Installing and building frontend"
          npm ci --prefix front
          npm run build --prefix front

      - name: Upload build artifact for debug
        uses: actions/upload-artifact@v4
        with:
          name: front-build-debug
          path: front/build

      - name: Show frontend directory & build output (debug)
        run: |
          echo "PWD: $(pwd)"
          echo "Listing front (top):" && ls -la front || true
          echo "Listing front/build (top):" && ls -la front/build || true
          echo "Count files in front/build:" && find front/build -type f | wc -l || true
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PROUD_ISLAND_00F144303 }}
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          # Upload only the already-built static site to avoid shipping the entire source tree
          # Use app_location as the repository folder and point the artifact location to the built output
          app_location: "front"
          api_location: "front/api" # Api source code path - optional
          # app_artifact_location is relative to app_location (which is 'front')
          app_artifact_location: "build"
          github_id_token: ${{ steps.idtoken.outputs.result }}
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: "close"
          skip_deploy_on_missing_secrets: true
